;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        comint-delchar-or-maybe-eof
        delete-horizontal-space
        delete-indentation
        downcase-dwim
        easy-kill
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        helm-confirm-and-exit-minibuffer
        helm-show-kill-ring
        indent-for-tab-command
        insert-char
        kill-region
        kill-sexp
        mark-sexp
        mu4e-headers-mark-for-read
        mu4e-mark-execute-all
        my/backward-kill-word-or-region
        org-beginning-of-line
        org-delete-char
        org-force-cycle-archived
        org-force-self-insert
        org-metaright
        org-self-insert-command
        org-todo
        orgtbl-self-insert-command
        paredit-backslash
        paredit-backward
        paredit-backward-kill-word
        paredit-close-square
        paredit-comment-dwim
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-open-square
        paredit-semicolon
        paredit-splice-sexp
        read-only-mode
        rjsx-delete-creates-full-tag
        shell-command-on-region
        sly-quit-completing
        sql-magic-go
        upcase-dwim
        wdired-exit
        wgrep-exit
        wgrep-finish-edit
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        goto-line
        helm-browse-project
        helm-find-files
        mouse-set-region
        rspec-verify
        ))
